version: "3.1"
services:

  database:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: marocShip
    ports:
        - "5432:5432"
    volumes:
        - ./data:/var/lib/postgresql/data

  web:
    image: tomcat
    container_name: tomcat-container
    ports:
      - "8088:8080"
    volumes:
      - ./target/macnssApp-1.0-SNAPSHOT.war:/usr/local/tomcat/webapps/ROOT.war

